# Generated by Django 6.1.1 on 2026-09-19 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenshot', models.ImageField(upload_to='job_screenshots/')),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('hr_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('raw_text', models.TextField(blank=True)),
                ('is_parsed', models.BooleanField(default=False)),
                ('parse_error', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
